
#Region " Option Statements "

Option Strict On
Option Explicit On
Option Infer Off

#End Region

#Region " Imports "

Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Text.Json.Serialization

Imports Ollamantis.Entities

#End Region

Namespace Contracts

#Region " ChatCompletionResponse "

    ''' <summary>
    ''' Represents the response containing the result of a <see cref="ChatCompletionRequest"/>.
    ''' </summary>
    ''' 
    ''' <remarks>
    ''' For additional information, visit the 
    ''' <see href="https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-chat-completion">
    ''' Ollama API documentation</see>.
    ''' </remarks>
    <EditorBrowsable(EditorBrowsableState.Always)>
    <Browsable(True)>
    <DebuggerStepThrough>
    <DebuggerDisplay("{DebuggerDisplay,nq}")>
    Public Class ChatCompletionResponse : Inherits GenerationResponseBase

#Region " Properties "

        ''' <summary>
        ''' Gets the message generated by the model.
        ''' </summary>
        <JsonIgnore(Condition:=JsonIgnoreCondition.WhenWritingNull)>
        <JsonPropertyName("message")>
        <DisplayName("Message")>
        <Description("The message generated by the model.")>
        Public ReadOnly Property Message As ChatMessage

#End Region

#Region " Constructors "

        ''' <summary>
        ''' Prevents a default instance of the <see cref="ChatCompletionResponse"/> class from being created.
        ''' </summary>
        Private Sub New()
        End Sub

        ''' <summary>
        ''' Initializes a new instance of the <see cref="ChatCompletionResponse"/> class.
        ''' </summary>
        ''' 
        ''' <param name="model">
        ''' The name of the model used for chat completion (e.g., "<c>llama3.2</c>").
        ''' </param>
        ''' 
        ''' <param name="createdAt">
        ''' The timestamp when the response was created, 
        ''' formatted as an ISO 8601 date and time string in UTC 
        ''' (e.g., "<c>2024-06-04T14:38:31.83753-07:00</c>").
        ''' </param>
        ''' 
        ''' <param name="done">
        ''' A <see cref="Boolean"/> value indicating the completion status of the response generation.
        ''' <para></para>
        ''' If streaming is disabled (<see cref="ChatCompletionRequest.Stream"/> = <see langword="False"/>), 
        ''' this will always be <see langword="True"/> since <see cref="ChatCompletionResponse.Message"/> 
        ''' contains the full streamed response.
        ''' <para></para>
        ''' If streaming is enabled (<see cref="ChatCompletionRequest.Stream"/> = <see langword="True"/>), 
        ''' this can be <see langword="False"/> if the response is still streaming,
        ''' or <see langword="True"/> if the response has finished streaming and 
        ''' <see cref="ChatCompletionResponse.Message"/> contains the final streamed chunk.
        ''' </param>
        ''' 
        ''' <param name="doneReason">
        ''' The completion reason of the response generation.
        ''' </param>
        ''' 
        ''' <param name="totalDuration">
        ''' The total time spent processing the entire request, in nanoseconds.
        ''' </param>
        ''' 
        ''' <param name="loadDuration">
        ''' The time spent loading the model, in nanoseconds.
        ''' </param>
        ''' 
        ''' <param name="promptEvalCount">
        ''' The number of tokens evaluated in the prompt.
        ''' </param>
        ''' 
        ''' <param name="promptEvalDuration">
        ''' The time spent evaluating the prompt, in nanoseconds.
        ''' </param>
        ''' 
        ''' <param name="evalCount">
        ''' The number of tokens generated in the response.
        ''' </param>
        ''' 
        ''' <param name="evalDuration">
        ''' The time spent strictly generating the response tokens, in nanoseconds.
        ''' </param>
        <JsonConstructor>
        Public Sub New(model As String,
                       message As ChatMessage,
                       createdAt As DateTimeOffset?,
                       done As Boolean?, doneReason As String,
                       totalDuration As Long?, loadDuration As Long?,
                       promptEvalCount As Integer?, promptEvalDuration As Long?,
                       evalCount As Integer?, evalDuration As Long?)

            MyBase.New(model:=model,
                       createdAt:=createdAt,
                       done:=done,
                       doneReason:=doneReason,
                       totalDuration:=totalDuration,
                       loadDuration:=loadDuration,
                       promptEvalCount:=promptEvalCount,
                       promptEvalDuration:=promptEvalDuration,
                       evalCount:=evalCount,
                       evalDuration:=evalDuration)

            Me.Message = message
        End Sub

#End Region

    End Class

#End Region

End Namespace
