
#Region " Option Statements "

Option Strict On
Option Explicit On
Option Infer Off

#End Region

#Region " Imports "

Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Text.Json
Imports System.Text.Json.Serialization

Imports Ollamantis.Core

#End Region

Namespace Entities

#Region " FunctionCall "

    ''' <summary>
    ''' Represents a function that an Ollama model wants to invoke inside a <see cref="ToolCall"/>.
    ''' </summary>
    ''' 
    ''' <remarks>
    ''' For additional information, visit the 
    ''' <see href="https://github.com/ollama/ollama/blob/main/docs/api.md#tool-calling">
    ''' Ollama API documentation</see>.
    ''' </remarks>
    <EditorBrowsable(EditorBrowsableState.Always)>
    <Browsable(True)>
    <DebuggerStepThrough>
    <DebuggerDisplay("Name = {Me.Name}, Arguments = {Me.Arguments.GetRawText()}")>
    Public Class FunctionCall : Inherits JsonObjectBaseImmutable

#Region " Properties "

        ''' <summary>
        ''' Gets the name of the function the model wants to call.
        ''' </summary>
        <JsonPropertyOrder(-1)> ' Forces this property to be serialized first (at top of JSON).
        <JsonPropertyName("name")>
        <DisplayName("Name")>
        <Description("The name of the function the model wants to call.")>
        Public ReadOnly Property Name As String

        ''' <summary>
        ''' Gets the key/value arguments generated by the model to pass to the function.
        ''' </summary>
        <JsonPropertyName("arguments")>
        <DisplayName("Arguments")>
        <Description("The key/value arguments generated by the model to pass to the function.")>
        Public ReadOnly Property Arguments As JsonElement

#End Region

#Region " Constructors "

        ''' <summary>
        ''' Prevents a default instance of the <see cref="FunctionCall"/> class from being created.
        ''' </summary>
        Private Sub New()
        End Sub

        ''' <summary>
        ''' Initializes a new instance of the <see cref="FunctionCall"/> class.
        ''' </summary>
        ''' 
        ''' <param name="name">
        ''' The name of the function the model wants to call (e.g., "<c>llama3.2</c>").
        ''' </param>
        ''' 
        ''' <param name="arguments">
        ''' The key/value arguments generated by the model to pass to the function. 
        ''' </param>
        <JsonConstructor>
        Public Sub New(name As String,
                       arguments As JsonElement)

            Me.Name = name
            Me.Arguments = arguments
        End Sub

#End Region

    End Class

#End Region

End Namespace
